# to install pre-commit: pre-commit install
# run pre-commit: pre-commit run --all-files
# ruff format
# ruff check || ruff check --fix
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
