# to install pre-commit: pre-commit install
# run pre-commit: pre-commit run --all-files
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix]  # Optional: automatically fix issues
        additional_dependencies: []
